### PR TITLE
Fix dates of migrated log entries:

### LINKED ISSUE #45: Log entries displayed on list table always show current time
Note: this was initially opened in AS repo with https://github.com/Prospress/action-scheduler/issues/178, but I'm 90% sure it's related only to custom tables now, so I'm opening it here instead.

---

The date/time displayed against log entries on the admin list table always show current time, not the time of the actual events.

For example, here are the log events displayed for the same scheduled action on the admin page loaded about 10 minutes apart:

1. Load at 2018-07-17 04:29:15 UTC: https://cl.ly/3p0V0u430s2b
1. Load at 2018-07-17 04:38:43 UTC: https://cl.ly/0T1I0r1y0o1t

Notice the times display on each change depending on the page load time, and all entries display the times the page was loaded.

I noticed this on ticket https://secure.helpscout.net/conversation/555708450/7375?folderId=1524436

I've also seen it on other sites.

### PR DESCRIPTION
**Pull request by rrennick**
Fixes #45 

- Move the log migration to occur before the action record is deleted
- Add the source log entry datetime to the destination log entry
- Include the log entry date when getting an existing log entry
- Unhook the default `action created` log entry which uses the current time

@thenbrent , @JPry do you think I should look at a way to re-hook the `action created` hooks after the batch is done?

### CODE REVIEW

File: src/Migration/Migration_Runner.php [hunk 1]
```diff
@@ -40,10 +42,11 @@ public function run( $batch_size = 10 ) {
 	public function migrate_actions( array $action_ids ) {
 		do_action( 'action_scheduler/custom_tables/migration_batch_starting', $action_ids );
 
+		remove_all_actions( 'action_scheduler_stored_action' );
```
Comment (thenbrent) [inline src/Migration/Migration_Runner.php]: Why remove all actions?

I think we only want to remove the _created date_ log entry, which could be done with something like:

```php
remove_action( 'action_scheduler_stored_action', array( ActionScheduler::logger(), 'log_stored_action', 10 ) );
```

File: src/Migration/Action_Migrator.php [hunk 2]
```diff
@@ -66,4 +69,8 @@ public function migrate( $source_action_id ) {
 			return $destination_action_id;
 		}
 	}
+
+	public function set_log_migrator( Log_Migrator $log_migrator ) {
```
Comment (thenbrent) [inline src/Migration/Action_Migrator.php]: Rather than a public setter, I think the `Log_Migrator` should be injected through the constructor to match the way the source & destination stores are injected.

That will mean the order of the `Action_Migrator` and `Log_Migrator`'s construction will need to be reversed in `Migration_Runner`, but I don't _think_ that will cause any issues.

The other option is to trigger a hook before `$this->source->delete_action( $source_action_id )`, but I do like the approach of calling `$this->log_migrator->migrate()` directly.

**Comment by rrennick** [comment]
@thenbrent Updated the PR per suggestions. Unit tests were also updated to use the new constructor. The one test failure was an instance of a timestamp being 1 second off.

**Comment by thenbrent** [comment]
@rrennick this is looking good. In answer to this:

> do you think I should look at a way to re-hook the action created hooks after the batch is done?

Yes, definitely. The migration can be run by Action Scheduler, in which case, if we don't re-hook the logging, we won't get logs for both the remaining events, like completion, on the `'action_scheduler/custom_tables/migration_hook'` action, as well as other actions run in the same queue.

**Comment by rrennick** [comment]
> It's probably a good idea to add new unhook()/hook() methods to handle this

See https://github.com/Prospress/action-scheduler/issues/247

I added re-hooking for now since the comment store functions need to be done in AS. When I migrate it over I'll update this code to use the new functions.

**Comment by thenbrent** [comment]
LGTM. 👍
